version: '3'

# To this file you will need docker and docker-compose installed.
# See this link for mac and windows: https://www.docker.com/products/docker-desktop
# On linux, you can probably use your package manager (apt, dnf, yum, etc.)

# (1) Download this file and save it as 'docker-compose.yml'
#
#  curl -o docker-compose.yml https://raw.githubusercontent.com/einsteintoolkit/jupyter-et/master/tutorial-server/docker-compose.user.yml

# (2) Start the server:
#
#  docker-compose up -d

# (3) Get the URL for the server
#
#  docker-compose logs
#
# You will see output of the form. Copy the URL and paste it in your browser.
#
# et-notebook | To access the notebook, open this file in a browser copy and paste this URL:
# et-notebook |
# et-notebook |  http://localhost:8888/?token=IHxGfgOO3P1efasL2s5BAtlC1haaG43X
# et-notebook |
# et-notebook | [I 14:13:24.359 NotebookApp] Serving notebooks from local directory: /home/jovyan


volumes:
    home_nbfs:

services:

  jup-et:
    image: einsteintoolkit/et-notebook
    hostname: et-notebook
    container_name: et-notebook
    ports:
      - 8888:8888
    volumes:
      - home_nbfs:/home
