version: '3'

volumes:
    home_fs21:

services:

  et-cyol:
    build:
        context: .
        dockerfile: cyol.docker
    image: et-cyol
    container_name: et-juphub
    hostname: etk1.cct.lsu.edu
    ports:
      - 443:443
    volumes:
      - /etc/ssl:/etc/ssl:Z
      - ./users:/users
      - home_fs21:/home
    restart: on-failure
    entrypoint: bash -x /startup.sh
    #entrypoint: sleep infinity
